# Generated by Django 4.2.24 on 2025-10-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='download_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='view_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
