# Generated by Django 4.2.24 on 2025-10-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic_analysis', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='topic_analysis.topic'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
