# Generated by Django 4.2.24 on 2025-10-21 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('time_range', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('topics', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_tasks', to='timetable.studyplan')),
            ],
            options={
                'ordering': ['day', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='DailyTask',
        ),
    ]
