# Generated by Django 4.2.24 on 2025-10-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timeslottask_delete_dailytask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslottask',
            old_name='time_range',
            new_name='duration',
        ),
    ]
