# Generated by Django 4.2.24 on 2025-10-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_material_download_url_material_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255)),
                ('difficulty_score', models.DecimalField(decimal_places=2, help_text='Difficulty score from 1.00 to 10.00', max_digits=4)),
                ('difficulty_class', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('summary', models.TextField(help_text="A short summary of the topic's content.")),
                ('sequence_number', models.PositiveIntegerField(help_text='The order in which the topic appears in the material.')),
                ('material', models.ForeignKey(help_text='The material this topic belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='materials.material')),
            ],
            options={
                'ordering': ['sequence_number'],
                'unique_together': {('material', 'sequence_number')},
            },
        ),
    ]
